name: CI/CD to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Go to project folder
          cd ${{ secrets.EC2_PATH }}

          # Pull latest code
          git pull origin main

          # Stop old containers
          docker-compose down

          # Remove unused images
          docker system prune -f

          # Rebuild and start
          docker-compose up -d --build